### ISSUE TITLE
Implement authentication

### ISSUE THREAD

**Issue by Raynos** [Raynos/raynos-blog#2]
You need user authentication

and a log in system

**Comment by Incognito** [comment]
Do you really? What if we did something cool like used keys.

**Comment by Raynos** [comment]
What do you mean by "keys" ?

I was going for generic session based user authorization and linking it up with users/roles in my database

**Comment by Incognito** [comment]
http://download.oracle.com/javaee/1.4/tutorial/doc/Security5.html

Scroll down to certificate-based authentication.

It requires you learn about SSL, and keys, as well as key generation. However, it could be a really cool way to lock down your blog: no user names, no passwords, no third-party auth.

**Comment by Raynos** [comment]
Authentication has been implemented.
